name: macOS

on:
  push:
    branches: [ master, macos ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  CI: 1

jobs:
  macos-build-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - macos-14
          - macos-15
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install pkg-config with Homebrew
      run: |
        brew install pkg-config mingw-w64 sccache llvm@15
        echo "$(brew --prefix llvm@15)/bin" >> $GITHUB_PATH

    - name: Build
      run: cargo build --release

    - name: Run tests
      run: cargo test --release