name: Rust CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  macos-build-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - macos-14
          - macos-15
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install pkg-config with Homebrew
      run: |
        brew install pkg-config mingw-w64 sccache llvm
        echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH

    - name: Build
      run: cargo build --release

    - name: Run tests
      run: cargo test --release
